# Setup
title:        Project or Site name
tagline:      A responsive theme for your project on GitHub Pages
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Duncan  Pringle
  url:        https://github.com/crysterbater

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
